### ISSUE TITLE
Having trouble with the command line

### ISSUE THREAD

**Issue by teknolog1k** [karlrees/docker_bedrockserver#6]
I have been trying to run a couple commands from the command line using `docker attach minecraft`, but there is no output, and running `stop` his way does not appear to stop the server. Finally, I can't find a way to exit out of this menu, as ^Q+^P doesn't work, and neither does  ^C. If the commands dont work at all, that's ok, but i would at least like a easier way to close the server gracefully, as my only current option is `docker stop/kill minecraft`

**Comment by karlrees** [comment]
When I wrote up the readme, I didn't anticipate needing to access the minecraft server console, so the example docker run commands did not keep stdin open or attach a tty.  I since realized I needed the console every once in a while, and consequently had changed the way I was running the containers, but never updated the readme and docker-compose files.  

So check out the updated readme now to see if it helps.  Thanks!
